version: '3.8'

services:
  db:
    build: ./oracle-db
    container_name: aquasos-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=senha123
    volumes:
      - oracle_data:/opt/oracle/oradata

  api:
    build: .
    container_name: aquasos-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=aquasos
      - SPRING_DATASOURCE_PASSWORD=aquasos123

volumes:
  oracle_data:
