spring.application.name=aquasos
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@oracle.fiap.com.br:1521/ORCL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:RM556859}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:141104}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true

spring.jpa.show-sql=true

# Swagger URL: http://localhost:8080/swagger-ui.html