spring.application.name=aquasos
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521/ORCL
spring.datasource.username=RM556859
spring.datasource.password=141104
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.show-sql=true

# Swagger URL: http://localhost:8080/swagger-ui.html